---
title: Kebijakan Publik Blog
email: admin@example.com
description: Wadah informasi kebijakan publik
theme: minima
permalink: /:year/:month/:day/:filename/
url: "https://ananggjr123-cmd.github.io"
---
